create_mock_module("litellm/llms/openai/chat/gpt_5_transformation.py", "class OpenAIGPT5Config: pass\n")
create_mock_module("litellm/llms/base_llm/chat/transformation.py", "class BaseConfig: pass\n")
create_mock_module("litellm/llms/base_llm/image_generation/transformation.py", "class BaseImageGenerationConfig: pass\n")
create_mock_module("litellm/llms/base_llm/base_model_iterator.py", "def convert_model_response_to_streaming(*a, **k): pass\n")
create_mock_module("litellm/llms/openai/chat/gpt_5_transformation.py", "class OpenAIGPT5Config: pass\n")
create_mock_module("litellm/llms/base_llm/chat/transformation.py", "class BaseConfig: pass\n")
create_mock_module("litellm/llms/base_llm/image_generation/transformation.py", "class BaseImageGenerationConfig: pass\n")
create_mock_module("litellm/llms/base_llm/base_model_iterator.py", "def convert_model_response_to_streaming(*a, **k): pass\n")
create_mock_module("litellm/llms/openai_like/json_loader.py", "class JSONProviderRegistry:\n    @staticmethod\n    def is_provider_in_registry(*a, **k): return False\n")
create_mock_module("litellm/llms/topaz/common_utils.py", "class TopazModelInfo:\n    pass\n")
create_mock_module("litellm/llms/topaz/chat/transformation.py", "class TopazConfig:\n    pass\n")
create_mock_module("litellm/llms/topaz/chat/__init__.py")
