import os
def create_mock_module(path, content=""):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)

create_mock_module("litellm/integrations/arize/arize_phoenix.py", "class ArizePhoenixLogger:\n    pass\n")
create_mock_module("litellm/integrations/datadog/__init__.py")
create_mock_module("litellm/integrations/datadog/datadog.py", "class DataDogLogger:\n    pass\n")

create_mock_module("litellm/integrations/azure_sentinel/__init__.py")
create_mock_module("litellm/integrations/azure_sentinel/azure_sentinel.py", "class AzureSentinelLogger:\n    pass\n")
create_mock_module("litellm/integrations/baseten.py", "class BasetenLogger:\n    pass\n")
create_mock_module("litellm/integrations/berris.py", "class BerrisLogger:\n    pass\n")
create_mock_module("litellm/integrations/cloud_flare_observability.py", "class CloudflareObservabilityLogger:\n    pass\n")
create_mock_module("litellm/integrations/context_window_hook.py", "class ContextWindowHook:\n    pass\n")
import shutil
try:
    os.remove("litellm/integrations/azure_storage.py")
except: pass
create_mock_module("litellm/integrations/azure_storage/__init__.py")
create_mock_module("litellm/integrations/azure_storage/azure_storage.py", "class AzureBlobStorageLogger:\n    pass\n")
create_mock_module("litellm/integrations/datadog/datadog_llm_obs.py", "class DataDogLLMObsLogger:\n    pass\n")
create_mock_module("litellm/integrations/elasticsearch/__init__.py")
create_mock_module("litellm/integrations/elasticsearch/elasticsearch.py", "class ElasticSearchLogger:\n    pass\n")
create_mock_module("litellm/integrations/kafka/__init__.py")
create_mock_module("litellm/integrations/kafka/kafka_logger.py", "class KafkaLogger:\n    pass\n")
create_mock_module("litellm/integrations/datadog/datadog_metrics.py", "class DatadogMetricsLogger:\n    pass\n")
create_mock_module("litellm/integrations/elastic_search_logger.py", "class ElasticSearchLogger:\n    pass\n")
create_mock_module("litellm/integrations/logos.py", "class LogosLogger:\n    pass\n")
create_mock_module("litellm/integrations/middle_tier_logger.py", "class MiddleTierLogger:\n    pass\n")
create_mock_module("litellm/integrations/dynamodb.py", "class DyanmoDBLogger:\n    pass\n")
create_mock_module("litellm/integrations/redis_metrics.py", "class RedisMetricsLogger:\n    pass\n")
create_mock_module("litellm/integrations/logstash.py", "class LogstashLogger:\n    pass\n")
create_mock_module("litellm/integrations/s3_storage/__init__.py")
create_mock_module("litellm/integrations/s3_storage/s3.py", "class S3StorageLogger:\n    pass\n")
create_mock_module("litellm/integrations/sagemaker_metrics.py", "class SagemakerMetricsLogger:\n    pass\n")
create_mock_module("litellm/integrations/galileo.py", "class GalileoLogger:\n    pass\nclass GalileoObserve:\n    pass\n")
create_mock_module("litellm/integrations/bento.py", "class BentoLogger:\n    pass\n")
create_mock_module("litellm/integrations/clearml.py", "class ClearMLLogger:\n    pass\n")
create_mock_module("litellm/integrations/gcs_bucket/gcs_bucket.py", "class GCSBucketLogger:\n    pass\n")
create_mock_module("litellm/integrations/langchain_community.py", "class LangchainCommunityLogger:\n    pass\n")
create_mock_module("litellm/integrations/pagerduty.py", "class PagerdutyLogger:\n    pass\n")
create_mock_module("litellm/integrations/gcs_pubsub/__init__.py")
create_mock_module("litellm/integrations/gcs_pubsub/pub_sub.py", "class GcsPubSubLogger:\n    pass\n")
create_mock_module("litellm/integrations/grafana.py", "class GrafanaLogger:\n    pass\n")
create_mock_module("litellm/integrations/statsd.py", "class StatsdLogger:\n    pass\n")
create_mock_module("litellm/integrations/greenscale.py", "class GreenscaleLogger:\n    pass\n")
create_mock_module("litellm/integrations/supabase_metrics.py", "class SupabaseMetricsLogger:\n    pass\n")
create_mock_module("litellm/integrations/traceloop_metrics.py", "class TraceloopMetricsLogger:\n    pass\n")
create_mock_module("litellm/integrations/humanloop/__init__.py", "class HumanloopLogger: pass\n")
create_mock_module("litellm/integrations/lago/__init__.py", "class LagoLogger: pass\n")
create_mock_module("litellm/integrations/prompt_layer/__init__.py", "class PromptLayerLogger: pass\n")
create_mock_module("litellm/integrations/datadog_llm_observability/__init__.py", "class DatadogLLMObservabilityLogger: pass\n")
create_mock_module("litellm/integrations/langchain/__init__.py", "class LangchainLogger: pass\n")
create_mock_module("litellm/integrations/open_telemetry/__init__.py", "class OpenTelemetryLogger: pass\n")
import os
try: os.remove("litellm/integrations/langfuse.py")
except: pass
create_mock_module("litellm/integrations/langfuse/__init__.py")
create_mock_module("litellm/integrations/langfuse/langfuse.py", "class LangFuseLogger: pass\n")
try: os.remove("litellm/integrations/logfire.py")
except: pass
create_mock_module("litellm/integrations/logfire/__init__.py")
create_mock_module("litellm/integrations/logfire/logfire.py", "class LogfireLogger: pass\n")
try: os.remove("litellm/integrations/lunary.py")
except: pass
create_mock_module("litellm/integrations/lunary/__init__.py")
create_mock_module("litellm/integrations/lunary/lunary.py", "class LunaryLogger: pass\n")
try: os.remove("litellm/integrations/open_meter.py")
except: pass
create_mock_module("litellm/integrations/open_meter/__init__.py")
create_mock_module("litellm/integrations/open_meter/open_meter.py", "class OpenMeterLogger: pass\n")
try: os.remove("litellm/integrations/s3.py")
except: pass
create_mock_module("litellm/integrations/s3/__init__.py")
create_mock_module("litellm/integrations/s3/s3.py", "class S3Logger: pass\n")
try: os.remove("litellm/integrations/sentry.py")
except: pass
create_mock_module("litellm/integrations/sentry/__init__.py")
create_mock_module("litellm/integrations/sentry/sentry.py", "class SentryLogger: pass\n")
try: os.remove("litellm/integrations/slack.py")
except: pass
create_mock_module("litellm/integrations/slack/__init__.py")
create_mock_module("litellm/integrations/slack/slack.py", "class SlackLogger: pass\n")
try: os.remove("litellm/integrations/supabase.py")
except: pass
create_mock_module("litellm/integrations/supabase/__init__.py")
create_mock_module("litellm/integrations/supabase/supabase.py", "class SupabaseLogger: pass\n")
try: os.remove("litellm/integrations/traceloop.py")
except: pass
create_mock_module("litellm/integrations/traceloop/__init__.py")
create_mock_module("litellm/integrations/traceloop/traceloop.py", "class TraceloopLogger: pass\n")
create_mock_module("litellm/integrations/langfuse/langfuse_handler.py", "class LangFuseHandler: pass\n")
create_mock_module("litellm/integrations/log10/log10.py", "class Log10Logger: pass\n")
create_mock_module("litellm/integrations/logfire/logfire_handler.py", "class LogfireHandler: pass\n")
create_mock_module("litellm/integrations/lunary/lunary_handler.py", "class LunaryHandler: pass\n")
create_mock_module("litellm/integrations/open_meter/open_meter_handler.py", "class OpenMeterHandler: pass\n")
create_mock_module("litellm/integrations/prometheus/prometheus.py", "class PrometheusLogger: pass\n")
create_mock_module("litellm/integrations/s3/s3_handler.py", "class S3Handler: pass\n")
create_mock_module("litellm/integrations/sentry/sentry_handler.py", "class SentryHandler: pass\n")
create_mock_module("litellm/integrations/slack/slack_handler.py", "class SlackHandler: pass\n")
create_mock_module("litellm/integrations/supabase/supabase_handler.py", "class SupabaseHandler: pass\n")
create_mock_module("litellm/integrations/traceloop/traceloop_handler.py", "class TraceloopHandler: pass\n")
create_mock_module("litellm/integrations/prometheus_metrics/prometheus_metrics.py", "class PrometheusMetricsLogger: pass\n")
create_mock_module("litellm/integrations/slack_alerting/slack_alerting.py", "class SlackAlertingLogger: pass\n")
create_mock_module("litellm/integrations/langfuse/langfuse_prompt_management.py", "class LangfusePromptManagement: pass\n")
create_mock_module("litellm/integrations/log10.py", "class Log10Logger: pass\n")
create_mock_module("litellm/integrations/log10/__init__.py")
create_mock_module("litellm/integrations/literal_ai.py", "class LiteralAILogger: pass\n")
create_mock_module("litellm/integrations/promptlayer.py", "class PromptLayerLogger: pass\n")
create_mock_module("litellm/integrations/datadog_llm_observability.py", "class DatadogLLMObservabilityLogger: pass\n")
create_mock_module("litellm/integrations/logfire_logger.py", "class LogfireLogger: pass\nclass LogfireLevel: pass\n")
create_mock_module("litellm/integrations/opentelemetry_logger.py", "class OpenTelemetryLogger: pass\n")
create_mock_module("litellm/integrations/prompt_tools_logger.py", "class PromptToolsLogger: pass\n")
create_mock_module("litellm/integrations/lunary/__init__.py", "class LunaryLogger: pass\n")
create_mock_module("litellm/integrations/lunary/lunary.py", "class LunaryLogger: pass\n")
create_mock_module("litellm/integrations/newrelic.py", "class NewRelicLogger: pass\n")
create_mock_module("litellm/integrations/one_apm.py", "class OneAPMLogger: pass\n")
create_mock_module("litellm/integrations/openmeter.py", "class OpenMeterLogger: pass\n")
create_mock_module("litellm/integrations/opik/__init__.py")
create_mock_module("litellm/integrations/opik/opik.py", "class OpikLogger: pass\n")
create_mock_module("litellm/integrations/posthog.py", "class PostHogLogger: pass\n")
create_mock_module("litellm/integrations/posthog_metrics.py", "class PosthogMetricsLogger: pass\n")
create_mock_module("litellm/integrations/s3/__init__.py", "class S3Logger: pass\n")
create_mock_module("litellm/integrations/supabase/__init__.py", "class SupabaseLogger: pass\n")
create_mock_module("litellm/integrations/traceloop/__init__.py", "class TraceloopLogger: pass\n")
create_mock_module("litellm/integrations/langsmith/__init__.py", "class LangsmithLogger: pass\n")
create_mock_module("litellm/integrations/datadog/__init__.py", "class DataDogLogger: pass\nclass DataDogLLMObsLogger: pass\n")
create_mock_module("litellm/integrations/sentry/__init__.py", "class SentryLogger: pass\n")
create_mock_module("litellm/integrations/s3_v2.py", "class S3Logger: pass\n")
create_mock_module("litellm/integrations/slack.py", "class SlackLogger: pass\n")
create_mock_module("litellm/integrations/wandb.py", "class WeightsBiasesLogger: pass\n")
create_mock_module("litellm/integrations/supabase/__init__.py", "class SupabaseLogger: pass\nclass Supabase: pass\n")
create_mock_module("litellm/integrations/datadog/__init__.py", "class DataDogLogger: pass\nclass DataDogLLMObsLogger: pass\nclass DatadogMetricsLogger: pass\nclass DatadogLogger: pass\n")
create_mock_module("litellm/llms/bedrock/common_utils.py", "class BedrockModelInfo:\n    @staticmethod\n    def get_bedrock_route(m): return 'unknown'\n    @staticmethod\n    def get_claude_platform_model(m): return m\n")
create_mock_module("litellm/llms/cohere/common_utils.py", "class CohereModelInfo:\n    @staticmethod\n    def get_cohere_route(m): return 'unknown'\n")
create_mock_module("litellm/llms/vertex_ai/common_utils.py", "class VertexAIModelRoute:\n    PARTNER_MODELS = 'partner_models'\n    GEMINI = 'gemini'\n    GEMMA = 'gemma'\n    MODEL_GARDEN = 'model_garden'\n    AGENT_ENGINE = 'agent_engine'\ndef get_vertex_ai_model_route(*a, **k): return 'unknown'\nclass VertexAIModelInfo: pass\ndef get_vertex_base_url(*a, **k): return ''\ndef redact_vertex_ai_metadata_from_litellm_params(*a, **k): pass\ndef redact_vertex_ai_metadata_from_logged_object(*a, **k): pass\n")
create_mock_module("litellm/llms/anthropic/chat/__init__.py", "class AnthropicChatCompletion: pass\n")
create_mock_module("litellm/llms/azure/audio_transcriptions.py", "class AzureAudioTranscription: pass\n")
create_mock_module("litellm/llms/azure/azure.py", "class AzureChatCompletion: pass\ndef _check_dynamic_azure_params(*a, **k): pass\nclass AzureOpenAIAssistantsAPIConfig: pass\n")
create_mock_module("litellm/llms/azure/chat/o_series_handler.py", "class AzureOpenAIO1ChatCompletion: pass\n")
create_mock_module("litellm/llms/azure/completion/handler.py", "class AzureTextCompletion: pass\n")
create_mock_module("litellm/llms/azure_ai/anthropic/handler.py", "class AzureAnthropicChatCompletion: pass\n")
create_mock_module("litellm/llms/azure_ai/embed.py", "class AzureAIEmbedding: pass\n")
create_mock_module("litellm/llms/bedrock/chat/__init__.py", "class BedrockConverseLLM: pass\nclass BedrockLLM: pass\n")
create_mock_module("litellm/llms/bedrock/embed/embedding.py", "class BedrockEmbedding: pass\n")
create_mock_module("litellm/llms/bedrock/image_edit/handler.py", "class BedrockImageEdit: pass\n")
create_mock_module("litellm/llms/bedrock/image_generation/image_handler.py", "class BedrockImageGeneration: pass\n")
create_mock_module("litellm/llms/bytez/chat/transformation.py", "class BytezChatConfig: pass\n")
create_mock_module("litellm/llms/clarifai/chat/transformation.py", "class ClarifaiConfig: pass\n")
create_mock_module("litellm/llms/codestral/completion/handler.py", "class CodestralTextCompletion: pass\n")
create_mock_module("litellm/llms/cohere/embed.py", "class handler: pass\n")
create_mock_module("litellm/llms/databricks/embed/handler.py", "class DatabricksEmbeddingHandler: pass\n")
create_mock_module("litellm/llms/gdc/chat/transformation.py", "class GDCGeminiConfig: pass\n")
create_mock_module("litellm/llms/groq/chat/handler.py", "class GroqChatCompletion: pass\n")
create_mock_module("litellm/llms/heroku/chat/transformation.py", "class HerokuChatConfig: pass\n")
create_mock_module("litellm/llms/huggingface/embedding/handler.py", "class HuggingFaceEmbedding: pass\n")
create_mock_module("litellm/llms/lemonade/chat/transformation.py", "class LemonadeChatConfig: pass\n")
create_mock_module("litellm/llms/nlp_cloud/chat/handler.py", "def completion(*a, **k): pass\n")
create_mock_module("litellm/llms/nvidia_riva/audio_transcription/handler.py", "class NvidiaRivaAudioTranscription: pass\n")
create_mock_module("litellm/llms/nvidia_riva/audio_transcription/transformation.py", "class NvidiaRivaAudioTranscriptionConfig: pass\n")
create_mock_module("litellm/llms/oci/chat/transformation.py", "class OCIChatConfig: pass\n")
create_mock_module("litellm/llms/ollama/completion.py", "class handler: pass\n")
create_mock_module("litellm/llms/oobabooga/chat.py", "class oobabooga: pass\n")
create_mock_module("litellm/llms/ovhcloud/chat/transformation.py", "class OVHCloudChatConfig: pass\n")
create_mock_module("litellm/llms/petals/completion.py", "class handler: pass\n")
create_mock_module("litellm/llms/predibase/chat/handler.py", "class PredibaseChatCompletion: pass\n")
create_mock_module("litellm/llms/replicate/chat/handler.py", "def completion(*a, **k): pass\n")
create_mock_module("litellm/llms/sagemaker/chat/handler.py", "class SagemakerChatHandler: pass\n")
create_mock_module("litellm/llms/sagemaker/completion/handler.py", "class SagemakerLLM: pass\n")
create_mock_module("litellm/llms/sap/chat/handler.py", "class GenAIHubOrchestration: pass\n")
create_mock_module("litellm/llms/vertex_ai.py", "class vertex_ai_non_gemini: pass\n")
create_mock_module("litellm/llms/vertex_ai/gemini/vertex_and_google_ai_studio_gemini.py", "class VertexLLM: pass\nclass VertexGeminiConfig: pass\n")
create_mock_module("litellm/llms/vertex_ai/gemini_embeddings/batch_embed_content_handler.py", "class VertexAIBatchEmbeddings: pass\n")
create_mock_module("litellm/llms/vertex_ai/image_generation/image_generation_handler.py", "class VertexAIImageGeneration: pass\n")
create_mock_module("litellm/llms/vertex_ai/multimodal_embeddings/embedding_handler.py", "class VertexAIMultimodalEmbeddings: pass\n")
create_mock_module("litellm/llms/vertex_ai/vertex_ai_partner_models/main.py", "class VertexAIPartnerModels: pass\n")
create_mock_module("litellm/llms/vertex_ai/vertex_embeddings/embedding_handler.py", "class VertexEmbedding: pass\n")
create_mock_module("litellm/llms/vertex_ai/vertex_gemma_models/main.py", "class VertexAIGemmaModels: pass\n")
create_mock_module("litellm/llms/vertex_ai/vertex_model_garden/main.py", "class VertexAIModelGardenModels: pass\n")
create_mock_module("litellm/llms/vllm/completion.py", "class handler: pass\n")
create_mock_module("litellm/llms/watsonx/chat/handler.py", "class WatsonXChatHandler: pass\n")
create_mock_module("litellm/llms/gemini/common_utils.py", "class GeminiModelInfo: pass\ndef get_gemini_base_url(*a, **k): return ''\ndef get_api_key_from_env(*a, **k): return ''\n")
create_mock_module("litellm/llms/oobabooga/chat/__init__.py", "class oobabooga: pass\n")
create_mock_module("litellm/llms/vertex_ai/__init__.py", "class vertex_ai_non_gemini: pass\n")
create_mock_module("litellm/llms/vertex_ai/gemini_embeddings/batch_embed_content_handler.py", "class VertexAIBatchEmbeddings: pass\nclass GoogleBatchEmbeddings: pass\n")
create_mock_module("litellm/llms/vertex_ai/image_generation/image_generation_handler.py", "class VertexAIImageGeneration: pass\nclass VertexImageGeneration: pass\n")
create_mock_module("litellm/llms/vertex_ai/multimodal_embeddings/embedding_handler.py", "class VertexAIMultimodalEmbeddings: pass\nclass VertexMultimodalEmbedding: pass\n")
create_mock_module("litellm/integrations/custom_logger.py", "class CustomLogger:\n    def __init__(self, *a, **k): pass\nclass Span:\n    pass\n")
