import os
import re

def create_mock_module(path, content=""):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)

llms_to_mock = [
    "anthropic", "bedrock", "cohere", "azure_ai", "github_copilot",
    "langgraph", "langflow", "soniox", "azure", "elevenlabs", "runwayml",
    "minimax", "aws_polly", "ai21", "aleph_alpha", "baseten", "cloudflare",
    "databricks", "deepinfra", "deepseek", "empower", "friendliai",
    "huggingface", "maritalk", "mistral", "nlp_cloud", "ollama", "openrouter",
    "palm", "perplexity", "petals", "replicate", "sagemaker", "together_ai",
    "vertex_ai", "voyage", "xai", "clarifai", "codestral", "dashscope",
    "gdc", "gemini", "groq", "heroku", "lemonade", "nvidia_riva", "oci",
    "oobabooga", "ovhcloud", "predibase", "sap", "vllm", "watsonx", "bytez",
    "aiml", "amazon_nova", "bedrock_mantle", "black_forest_labs", "chatgpt",
    "cometapi", "fal_ai", "fireworks_ai", "gigachat", "hosted_vllm", "litellm_proxy",
    "modelscope", "openai_like", "recraft", "reducto", "stability", "tencent", "deprecated_providers"
]

for llm in llms_to_mock:
    create_mock_module(f"litellm/llms/{llm}/__init__.py")

# Specific files needed
create_mock_module("litellm/llms/anthropic/common_utils.py", "class AnthropicModelInfo:\n    pass\n")
create_mock_module("litellm/llms/anthropic/chat/transformation.py", "class AnthropicConfig:\n    pass\n")
create_mock_module("litellm/llms/bedrock/chat/invoke_handler.py", "class BedrockGlobalConfig: pass\nbedrock_tool_name_mappings = {}\nclass MockResponseIterator:\n    def __init__(self, *a, **k): pass\n    def __iter__(self): return self\n    def __next__(self): raise StopIteration\n")
create_mock_module("litellm/llms/cohere/chat/transformation.py", "class CohereGlobalConfig:\n    pass\nclass CohereConfig:\n    pass\n")
create_mock_module("litellm/llms/vertex_ai/text_embeddings/transformation.py", "class VertexAITextEmbeddingConfig:\n    pass\n")
create_mock_module("litellm/llms/sagemaker/chat/transformation.py", "class SagemakerConfig:\n    pass\n")
create_mock_module("litellm/llms/petals/chat/transformation.py", "class PetalsConfig:\n    pass\n")
create_mock_module("litellm/llms/nlp_cloud/chat/transformation.py", "class NLPCloudConfig:\n    pass\n")
create_mock_module("litellm/llms/replicate/chat/transformation.py", "class ReplicateConfig:\n    pass\n")
create_mock_module("litellm/llms/databricks/chat/transformation.py", "class DatabricksConfig:\n    pass\n")
create_mock_module("litellm/llms/empower/chat/transformation.py", "class EmpowerConfig:\n    pass\n")
create_mock_module("litellm/llms/ai21/chat/transformation.py", "class AI21ChatConfig:\n    pass\nAI21Config = AI21ChatConfig\n")
create_mock_module("litellm/llms/deprecated_providers/palm.py", "class PalmConfig:\n    pass\n")
create_mock_module("litellm/llms/deprecated_providers/aleph_alpha.py", "class AlephAlphaConfig:\n    pass\n")
create_mock_module("litellm/llms/baseten/chat/transformation.py", "class BasetenConfig:\n    pass\n")
create_mock_module("litellm/llms/cloudflare/chat/transformation.py", "class CloudflareChatConfig:\n    pass\nCloudflareConfig = CloudflareChatConfig\n")
create_mock_module("litellm/llms/gemini/common_utils.py", "class GeminiModelInfo: pass\ndef get_gemini_base_url(*a, **k): return ''\n")
create_mock_module("litellm/llms/gemini/chat/transformation.py", "class GeminiConfig:\n    pass\n")
create_mock_module("litellm/llms/huggingface/chat/transformation.py", "class HuggingfaceConfig:\n    pass\n")
create_mock_module("litellm/llms/oobabooga/chat/transformation.py", "class OobaboogaConfig:\n    pass\n")
create_mock_module("litellm/llms/openrouter/chat/transformation.py", "class OpenrouterConfig:\n    pass\n")
create_mock_module("litellm/llms/together_ai/chat/transformation.py", "class TogetherAIConfig:\n    pass\n")
create_mock_module("litellm/llms/vertex_ai/chat/transformation.py", "class VertexAIConfig:\n    pass\n")
create_mock_module("litellm/llms/maritalk/chat/transformation.py", "class MaritalkConfig:\n    pass\n")
create_mock_module("litellm/llms/anthropic/cost_calculation.py", "def cost_per_token(*a, **k): return 0.0, 0.0\n")
create_mock_module("litellm/llms/bedrock/cost_calculator.py", "def cost_per_token(*a, **k): return 0.0, 0.0\ndef cost_per_character(*a, **k): return 0.0, 0.0\n")
create_mock_module("litellm/llms/azure/cost_calculation.py", "def cost_per_token(*a, **k): return 0.0, 0.0\n")
create_mock_module("litellm/llms/cohere/cost_calculator.py", "def cost_per_token(*a, **k): return 0.0, 0.0\n")
create_mock_module("litellm/llms/vertex_ai/cost_calculator.py", "def cost_per_token(*a, **k): return 0.0, 0.0\ndef get_cost_for_web_search_request(*a, **k): return 0.0\ndef cost_per_character(*a, **k): return 0.0, 0.0\nclass _CostRouter:\n    def __init__(self, *a, **k): pass\n    def get_cost(*a, **k): return 0.0, 0.0\ncost_router = _CostRouter()\n")
create_mock_module("litellm/llms/openai/cost_calculator.py", "def cost_per_token(*a, **k): return 0.0, 0.0\n")
create_mock_module("litellm/llms/azure_ai/cost_calculator.py", "def cost_per_token(*a, **k): return 0.0, 0.0\n")
create_mock_module("litellm/llms/gemini/cost_calculator.py", "def cost_per_token(*a, **k): return 0.0, 0.0\ndef get_cost_for_web_search_request(*a, **k): return 0.0\n")
create_mock_module("litellm/llms/bedrock/cost_calculation.py", "def cost_per_token(*a, **k): return 0.0, 0.0\n")
create_mock_module("litellm/llms/sagemaker/cost_calculator.py", "def cost_per_token(*a, **k): return 0.0, 0.0\n")
create_mock_module("litellm/llms/vertex_ai/cost_calculation.py", "def cost_per_token(*a, **k): return 0.0, 0.0\ndef get_cost_for_web_search_request(*a, **k): return 0.0\n")
create_mock_module("litellm/llms/cohere/cost_calculation.py", "def cost_per_token(*a, **k): return 0.0, 0.0\n")
create_mock_module("litellm/llms/gemini/cost_calculation.py", "def cost_per_token(*a, **k): return 0.0, 0.0\ndef get_cost_for_web_search_request(*a, **k): return 0.0\n")
create_mock_module("litellm/llms/databricks/cost_calculator.py", "def cost_per_token(*a, **k): return 0.0, 0.0\n")
create_mock_module("litellm/llms/ollama/cost_calculator.py", "def cost_per_token(*a, **k): return 0.0, 0.0\n")
create_mock_module("litellm/llms/replicate/cost_calculator.py", "def cost_per_token(*a, **k): return 0.0, 0.0\n")
create_mock_module("litellm/llms/deepseek/cost_calculator.py", "def cost_per_token(*a, **k): return 0.0, 0.0\n")
create_mock_module("litellm/llms/tencent/cost_calculator.py", "def cost_per_token(*a, **k): return 0.0, 0.0\n")
create_mock_module("litellm/llms/huggingface/cost_calculator.py", "def cost_per_token(*a, **k): return 0.0, 0.0\n")
create_mock_module("litellm/llms/fireworks_ai/cost_calculator.py", "def cost_per_token(*a, **k): return 0.0, 0.0\n")
create_mock_module("litellm/llms/hosted_vllm/cost_calculator.py", "def cost_per_token(*a, **k): return 0.0, 0.0\n")
create_mock_module("litellm/llms/github_copilot/cost_calculator.py", "def cost_per_token(*a, **k): return 0.0, 0.0\n")
create_mock_module("litellm/llms/chatgpt/cost_calculator.py", "def cost_per_token(*a, **k): return 0.0, 0.0\n")
create_mock_module("litellm/llms/gigachat/cost_calculator.py", "def cost_per_token(*a, **k): return 0.0, 0.0\n")
create_mock_module("litellm/llms/lemonade/cost_calculator.py", "def cost_per_token(*a, **k): return 0.0, 0.0\n")
create_mock_module("litellm/llms/amazon_nova/cost_calculator.py", "def cost_per_token(*a, **k): return 0.0, 0.0\n")
create_mock_module("litellm/llms/bedrock_mantle/cost_calculator.py", "def cost_per_token(*a, **k): return 0.0, 0.0\n")
create_mock_module("litellm/llms/perplexity/cost_calculator.py", "def cost_per_token(*a, **k): return 0.0, 0.0\n")
create_mock_module("litellm/llms/together_ai/cost_calculator.py", "def cost_per_token(*a, **k): return 0.0, 0.0\ndef get_model_params_and_category(*a, **k): return None, None\n")
create_mock_module("litellm/llms/xai/cost_calculator.py", "def cost_per_token(*a, **k): return 0.0, 0.0\n")
create_mock_module("litellm/llms/groq/cost_calculator.py", "def cost_per_token(*a, **k): return 0.0, 0.0\n")
create_mock_module("litellm/llms/clarifai/cost_calculator.py", "def cost_per_token(*a, **k): return 0.0, 0.0\n")
create_mock_module("litellm/llms/openai_like/json_loader.py", "class JSONProviderRegistry:\n    @staticmethod\n    def is_provider_in_registry(*a, **k): return False\n")
create_mock_module("litellm/llms/xai/common_utils.py", "class XAIModelInfo:\n    @staticmethod\n    def is_xai_route(*a, **k): return False\n")
create_mock_module("litellm/llms/azure/realtime/handler.py", "class AzureOpenAIRealtime: pass\n")
create_mock_module("litellm/llms/bedrock/realtime/handler.py", "class BedrockRealtime: pass\n")
create_mock_module("litellm/llms/gemini/realtime/handler.py", "class GeminiRealtime: pass\n")
create_mock_module("litellm/llms/openai/realtime/handler.py", "class OpenAIRealtime: pass\n")
create_mock_module("litellm/llms/vertex_ai/realtime/transformation.py", "class VertexAIRealtimeConfig: pass\n")
create_mock_module("litellm/llms/vertex_ai/vertex_llm_base.py", "class VertexBase:\n    def __init__(self, *a, **k): pass\n    def _get_vertex_auth(self, *a, **k): return 'a', 'b'\n    def _get_vertex_region_and_project_id(self, *a, **k): return 'a', 'b'\n    async def _aget_vertex_auth(self, *a, **k): return 'a', 'b'\n")
create_mock_module("litellm/llms/xai/realtime/handler.py", "class XAIRealtime: pass\n")
create_mock_module("litellm/llms/openai_like/chat/handler.py", "class OpenAILikeChatHandler: pass\n")
create_mock_module("litellm/llms/openai_like/embedding/handler.py", "class OpenAILikeEmbeddingHandler: pass\n")
create_mock_module("litellm/llms/litellm_proxy/chat/handler.py", "class LiteLLMProxyChatHandler: pass\n")
create_mock_module("litellm/llms/azure/assistants.py", "class AzureAssistantsAPI:\n    pass\n")
create_mock_module("litellm/llms/anthropic/batches/handler.py", "class AnthropicBatchesHandler:\n    def __init__(self, *a, **k): pass\n")
create_mock_module("litellm/llms/azure/batches/handler.py", "class AzureBatchesAPI:\n    def __init__(self, *a, **k): pass\n")
create_mock_module("litellm/llms/bedrock/batches/handler.py", "class BedrockBatchesHandler:\n    def __init__(self, *a, **k): pass\nclass BedrockBatchesAPI:\n    def __init__(self, *a, **k): pass\n")
create_mock_module("litellm/llms/vertex_ai/batches/handler.py", "class VertexBatchesAPI:\n    pass\nclass VertexBatchesHandler:\n    pass\nclass VertexAIBatchesHandler:\n    pass\nclass VertexAIBatchPrediction:\n    def __init__(self, *a, **k): pass\n")
create_mock_module("litellm/llms/black_forest_labs/image_edit/handler.py", "class _BFLImageEdit:\n    pass\nbfl_image_edit = _BFLImageEdit()\n")
create_mock_module("litellm/llms/recraft/image_edit/handler.py", "class _RecraftImageEdit:\n    pass\nrecraft_image_edit = _RecraftImageEdit()\n")
create_mock_module("litellm/llms/azure_ai/image_edit.py", "class _AzureAIImageEdit:\n    pass\nazure_ai_image_edit = _AzureAIImageEdit()\n")
create_mock_module("litellm/llms/black_forest_labs/image_generation/handler.py", "bfl_image_generation = type('Dummy', (), {})()\n")
create_mock_module("litellm/llms/recraft/image_generation/handler.py", "recraft_image_generation = type('Dummy', (), {})()\n")
create_mock_module("litellm/llms/azure_ai/image_generation.py", "azure_ai_image_generation = type('Dummy', (), {})()\n")
create_mock_module("litellm/llms/fal_ai/image_generation/handler.py", "fal_ai_image_generation = type('Dummy', (), {})()\n")
create_mock_module("litellm/llms/aiml/image_generation/handler.py", "aiml_image_generation = type('Dummy', (), {})()\n")
create_mock_module("litellm/llms/cometapi/image_generation/handler.py", "cometapi_image_generation = type('Dummy', (), {})()\n")
create_mock_module("litellm/llms/stability/image_generation/handler.py", "stability_image_generation = type('Dummy', (), {})()\n")
create_mock_module("litellm/llms/stability/image_edit/handler.py", "stability_image_edit = type('Dummy', (), {})()\n")
create_mock_module("litellm/llms/runwayml/image_generation/handler.py", "runwayml_image_generation = type('Dummy', (), {})()\n")
create_mock_module("litellm/llms/openrouter/image_generation.py", "openrouter_image_generation = type('Dummy', (), {})()\n")
create_mock_module("litellm/llms/openrouter/image_edit.py", "openrouter_image_edit = type('Dummy', (), {})()\n")
create_mock_module("litellm/llms/dashscope/image_generation.py", "dashscope_image_generation = type('Dummy', (), {})()\n")
create_mock_module("litellm/llms/modelscope/image_generation.py", "modelscope_image_generation = type('Dummy', (), {})()\n")
create_mock_module("litellm/llms/gemini/image_generation/handler.py", "gemini_image_generation = type('Dummy', (), {})()\n")
create_mock_module("litellm/llms/gemini/image_edit.py", "gemini_image_edit = type('Dummy', (), {})()\n")
create_mock_module("litellm/llms/vertex_ai/image_edit.py", "vertex_image_edit = type('Dummy', (), {})()\n")
create_mock_module("litellm/llms/vllm/completion/handler.py", "class _VllmHandler:\n    def batch_pt(*a, **k): pass\nhandler = _VllmHandler()\n")
create_mock_module("litellm/llms/bedrock/rerank/handler.py", "class BedrockRerankHandler: pass\n")
create_mock_module("litellm/llms/cohere/rerank/handler.py", "class CohereRerankHandler: pass\nclass CohereRerank: pass\n")
create_mock_module("litellm/llms/dashscope/rerank/handler.py", "class DashScopeRerankHandler: pass\nclass DashScopeRerank: pass\n")
create_mock_module("litellm/llms/together_ai/rerank/handler.py", "class TogetherAIRerankHandler: pass\nclass TogetherAIRerank: pass\n")
create_mock_module("litellm/llms/voyage/rerank/handler.py", "class VoyageRerankHandler: pass\nclass VoyageRerank: pass\n")
create_mock_module("litellm/llms/watsonx/common_utils.py", "class IBMWatsonXMixin: pass\n")
create_mock_module("litellm/llms/vertex_ai/rerank/handler.py", "class VertexAIRerankHandler: pass\nclass VertexAIRerank: pass\n")
create_mock_module("litellm/llms/azure_ai/ocr/common_utils.py", "class AzureAIOCRConfig: pass\ndef get_azure_ai_ocr_config(*a, **k): return None\ndef is_azure_document_intelligence_model(*a, **k): return False\n")
create_mock_module("litellm/llms/vertex_ai/ocr/common_utils.py", "class VertexAIOCRConfig: pass\ndef get_vertex_ai_ocr_config(*a, **k): return None\ndef is_vertex_ai_ocr_model(*a, **k): return False\n")
create_mock_module("litellm/llms/reducto/ocr/transformation.py", "class ReductoOCRConfig: pass\n")
create_mock_module("litellm/llms/bedrock/base_aws_llm.py", "class BaseAWSLLM:\n    pass\n")
create_mock_module("litellm/llms/vertex_ai/common_utils.py", "class VertexAIModelInfo: pass\ndef get_vertex_base_url(*a, **k): return ''\n")
create_mock_module("litellm/llms/azure/fine_tuning/handler.py", "class AzureOpenAIFineTuningAPI: pass\n")
create_mock_module("litellm/llms/vertex_ai/fine_tuning/handler.py", "class VertexFineTuningAPI: pass\n")
create_mock_module("litellm/llms/azure/common_utils.py", "def get_azure_credentials(*a, **k): return None\n")
create_mock_module("litellm/llms/azure/files/handler.py", "class AzureOpenAIFilesAPI: pass\n")
create_mock_module("litellm/llms/bedrock/files/handler.py", "class BedrockFilesHandler: pass\n")
create_mock_module("litellm/llms/vertex_ai/files/handler.py", "class VertexAIFilesHandler: pass\n")
create_mock_module("litellm/llms/anthropic/experimental_pass_through/messages/handler.py", "class AsyncAnthropicMessagesHandler:\n    def __init__(self, *a, **k): pass\nclass AnthropicMessagesHandler:\n    def __init__(self, *a, **k): pass\ndef anthropic_messages(*a, **k): pass\nasync_anthropic_messages_handler = AsyncAnthropicMessagesHandler()\nanthropic_messages_handler = AnthropicMessagesHandler()\n")

print("Created mocks")
create_mock_module("litellm/llms/topaz/common_utils.py", "class TopazModelInfo:\n    pass\n")
create_mock_module("litellm/llms/topaz/chat/transformation.py", "class TopazConfig:\n    pass\n")
create_mock_module("litellm/llms/topaz/chat/__init__.py")
create_mock_module("litellm/llms/vertex_ai/common_utils.py", "class VertexAIModelInfo: pass\ndef get_vertex_base_url(*a, **k): return ''\ndef redact_vertex_ai_metadata_from_litellm_params(*a, **k): pass\n")
create_mock_module("litellm/llms/vertex_ai/common_utils.py", "class VertexAIModelInfo: pass\ndef get_vertex_base_url(*a, **k): return ''\ndef redact_vertex_ai_metadata_from_litellm_params(*a, **k): pass\ndef redact_vertex_ai_metadata_from_logged_object(*a, **k): pass\n")
create_mock_module("litellm/integrations/agentops.py", "class AgentOps:\n    pass\n")
create_mock_module("litellm/integrations/aisera.py", "class AiseraLogger:\n    pass\n")
create_mock_module("litellm/integrations/anthropic_bedrock_logging.py", "class AnthropicBedrockLogger:\n    pass\n")
create_mock_module("litellm/integrations/aporia.py", "class AporiaLogger:\n    pass\n")
create_mock_module("litellm/integrations/argilla.py", "class ArgillaLogger:\n    pass\n")
create_mock_module("litellm/integrations/athina.py", "class AthinaLogger:\n    pass\n")
create_mock_module("litellm/integrations/azure_storage.py", "class AzureStorageLogger:\n    pass\n")
create_mock_module("litellm/integrations/braintrust.py", "class BraintrustLogger:\n    pass\n")
create_mock_module("litellm/integrations/clickhouse.py", "class ClickhouseLogger:\n    pass\n")
create_mock_module("litellm/integrations/comet.py", "class CometLogger:\n    pass\n")
create_mock_module("litellm/integrations/datadog.py", "class DatadogLogger:\n    pass\n")
create_mock_module("litellm/integrations/datahub.py", "class DatahubLogger:\n    pass\n")
create_mock_module("litellm/integrations/digital_ocean_space.py", "class DigitalOceanSpaceLogger:\n    pass\n")
create_mock_module("litellm/integrations/dynatrace.py", "class DynatraceLogger:\n    pass\n")
create_mock_module("litellm/integrations/galileo.py", "class GalileoLogger:\n    pass\n")
create_mock_module("litellm/integrations/gcs.py", "class GCSLogger:\n    pass\n")
create_mock_module("litellm/integrations/generic_api_callback.py", "class GenericApiLogger:\n    pass\n")
create_mock_module("litellm/integrations/greenguard.py", "class GreenguardLogger:\n    pass\n")
create_mock_module("litellm/integrations/helicone.py", "class HeliconeLogger:\n    pass\n")
create_mock_module("litellm/integrations/langfuse.py", "class LangfuseLogger:\n    pass\n")
create_mock_module("litellm/integrations/langsmith.py", "class LangsmithLogger:\n    pass\n")
create_mock_module("litellm/integrations/llama_index.py", "class LlamaIndexLogger:\n    pass\n")
create_mock_module("litellm/integrations/log10.py", "class Log10Logger:\n    pass\n")
create_mock_module("litellm/integrations/logfire.py", "class LogfireLogger:\n    pass\n")
create_mock_module("litellm/integrations/lunary.py", "class LunaryLogger:\n    pass\n")
create_mock_module("litellm/integrations/open_meter.py", "class OpenMeterLogger:\n    pass\n")
create_mock_module("litellm/integrations/opentelemetry.py", "class OpenTelemetryLogger:\n    pass\nOpenTelemetry = OpenTelemetryLogger\n")
create_mock_module("litellm/integrations/parse_data.py", "class ParseDataLogger:\n    pass\n")
create_mock_module("litellm/integrations/posthog.py", "class PosthogLogger:\n    pass\n")
create_mock_module("litellm/integrations/prometheus.py", "class PrometheusLogger:\n    pass\n")
create_mock_module("litellm/integrations/s3.py", "class S3Logger:\n    pass\n")
create_mock_module("litellm/integrations/sentry.py", "class SentryLogger:\n    pass\n")
create_mock_module("litellm/integrations/slack.py", "class SlackLogger:\n    pass\n")
create_mock_module("litellm/integrations/supabase.py", "class SupabaseLogger:\n    pass\n")
create_mock_module("litellm/integrations/traceloop.py", "class TraceloopLogger:\n    pass\n")
create_mock_module("litellm/integrations/weights_biases.py", "class WeightsBiasesLogger:\n    pass\n")
create_mock_module("litellm/integrations/anthropic_cache_control_hook.py", "class AnthropicCacheControlHook:\n    pass\n")
create_mock_module("litellm/integrations/langsmith_config.py", "class LangsmithConfig:\n    pass\n")
create_mock_module("litellm/integrations/azure_storage_config.py", "class AzureStorageConfig:\n    pass\n")
create_mock_module("litellm/integrations/custom_logger.py", "class CustomLogger:\n    pass\n")
create_mock_module("litellm/integrations/slack_config.py", "class SlackConfig:\n    pass\n")
create_mock_module("litellm/integrations/arize/__init__.py")
create_mock_module("litellm/integrations/arize/arize.py", "class ArizeLogger:\n    pass\n")
create_mock_module("litellm/integrations/deepeval/__init__.py")
create_mock_module("litellm/integrations/deepeval/deepeval.py", "class DeepEvalLogger:\n    pass\n")
create_mock_module("litellm/integrations/honeycomb/__init__.py")
create_mock_module("litellm/integrations/honeycomb/honeycomb.py", "class HoneycombLogger:\n    pass\n")
create_mock_module("litellm/integrations/humanloop/__init__.py")
create_mock_module("litellm/integrations/humanloop/humanloop.py", "class HumanloopLogger:\n    pass\n")
create_mock_module("litellm/integrations/lago/__init__.py")
create_mock_module("litellm/integrations/lago/lago.py", "class LagoLogger:\n    pass\n")
create_mock_module("litellm/integrations/prompt_layer/__init__.py")
create_mock_module("litellm/integrations/prompt_layer/prompt_layer.py", "class PromptLayerLogger:\n    pass\n")
create_mock_module("litellm/integrations/datadog_llm_observability/__init__.py")
create_mock_module("litellm/integrations/datadog_llm_observability/datadog_llm_observability.py", "class DatadogLLMObservabilityLogger:\n    pass\n")
create_mock_module("litellm/integrations/langchain/__init__.py")
create_mock_module("litellm/integrations/langchain/langchain.py", "class LangchainLogger:\n    pass\n")
create_mock_module("litellm/integrations/open_telemetry/__init__.py")
create_mock_module("litellm/integrations/open_telemetry/open_telemetry.py", "class OpenTelemetryLogger:\n    pass\n")
create_mock_module("litellm/integrations/mlflow.py", "class MlflowLogger:\n    pass\n")
create_mock_module("litellm/integrations/presidio.py", "class PresidioLogger:\n    pass\n")
create_mock_module("litellm/integrations/sagemaker.py", "class SagemakerLogger:\n    pass\n")
create_mock_module("litellm/integrations/upstash.py", "class UpstashLogger:\n    pass\n")
create_mock_module("litellm/integrations/prompt_tools.py", "class PromptToolsLogger:\n    pass\n")
create_mock_module("litellm/integrations/sqs.py", "class SQSLogger:\n    pass\n")
create_mock_module("litellm/integrations/slack_alerting.py", "class SlackAlerting:\n    pass\n")
create_mock_module("litellm/integrations/datadog_metrics.py", "class DatadogMetrics:\n    pass\n")
create_mock_module("litellm/integrations/prometheus_metrics.py", "class PrometheusMetrics:\n    pass\n")
create_mock_module("litellm/llms/bedrock/chat/converse_transformation.py", "class BedrockConverseConfig:\n    pass\nclass AmazonConverseConfig:\n    def _get_cache_point_block(*a, **k): return None\n")
create_mock_module("litellm/llms/bedrock/chat/__init__.py")
create_mock_module("litellm/integrations/galileo.py", "class GalileoLogger:\n    pass\nclass GalileoObserve: pass\n")
create_mock_module("litellm/integrations/humanloop/__init__.py", "class HumanloopLogger: pass\n")
create_mock_module("litellm/integrations/lago/__init__.py", "class LagoLogger: pass\n")
create_mock_module("litellm/integrations/langfuse/__init__.py", "class LangFuseLogger: pass\n")
create_mock_module("litellm/integrations/logfire/__init__.py", "class LogfireLogger: pass\nclass LogfireLevel: pass\n")
create_mock_module("litellm/integrations/lunary/__init__.py", "class LunaryLogger: pass\n")
create_mock_module("litellm/integrations/open_meter/__init__.py", "class OpenMeterLogger: pass\n")
create_mock_module("litellm/integrations/opik/__init__.py", "class OpikLogger: pass\n")
create_mock_module("litellm/integrations/posthog.py", "class PostHogLogger: pass\n")
create_mock_module("litellm/integrations/s3/__init__.py", "class S3Logger: pass\n")
create_mock_module("litellm/integrations/sentry/__init__.py", "class SentryLogger: pass\n")
create_mock_module("litellm/integrations/slack/__init__.py", "class SlackLogger: pass\n")
create_mock_module("litellm/integrations/supabase/__init__.py", "class SupabaseLogger: pass\nclass Supabase: pass\n")
create_mock_module("litellm/integrations/traceloop/__init__.py", "class TraceloopLogger: pass\n")
create_mock_module("litellm/integrations/prompt_layer/__init__.py", "class PromptLayerLogger: pass\n")
create_mock_module("litellm/integrations/datadog_llm_observability/__init__.py", "class DatadogLLMObservabilityLogger: pass\n")
create_mock_module("litellm/integrations/langchain/__init__.py", "class LangchainLogger: pass\n")
create_mock_module("litellm/integrations/open_telemetry/__init__.py", "class OpenTelemetryLogger: pass\n")
create_mock_module("litellm/integrations/datadog/__init__.py", "class DataDogLogger: pass\nclass DataDogLLMObsLogger: pass\nclass DatadogMetricsLogger: pass\nclass DatadogLogger: pass\n")
create_mock_module("litellm/llms/vertex_ai/common_utils.py", "class VertexAIModelRoute:\n    PARTNER_MODELS = 'partner_models'\n    GEMINI = 'gemini'\n    GEMMA = 'gemma'\n    MODEL_GARDEN = 'model_garden'\n    AGENT_ENGINE = 'agent_engine'\ndef get_vertex_ai_model_route(*a, **k): return 'unknown'\nclass VertexAIModelInfo: pass\ndef get_vertex_base_url(*a, **k): return ''\ndef redact_vertex_ai_metadata_from_litellm_params(*a, **k): pass\ndef redact_vertex_ai_metadata_from_logged_object(*a, **k): pass\n")
create_mock_module("litellm/llms/bedrock/chat/__init__.py", "class BedrockConverseLLM: pass\nclass BedrockLLM: pass\n")
create_mock_module("litellm/llms/anthropic/chat/__init__.py", "class AnthropicChatCompletion: pass\n")
create_mock_module("litellm/llms/cohere/embed.py", "class handler: pass\n")
create_mock_module("litellm/llms/ollama/completion.py", "class handler: pass\n")
create_mock_module("litellm/llms/oobabooga/chat.py", "class oobabooga: pass\n")
create_mock_module("litellm/llms/petals/completion.py", "class handler: pass\n")
create_mock_module("litellm/llms/vllm/completion.py", "class handler: pass\n")
create_mock_module("litellm/llms/gemini/common_utils.py", "class GeminiModelInfo: pass\ndef get_gemini_base_url(*a, **k): return ''\ndef get_api_key_from_env(*a, **k): return ''\n")
create_mock_module("litellm/llms/oobabooga/chat/__init__.py", "class oobabooga: pass\n")
create_mock_module("litellm/llms/vertex_ai/__init__.py", "class vertex_ai_non_gemini: pass\n")
create_mock_module("litellm/llms/vertex_ai/gemini_embeddings/batch_embed_content_handler.py", "class VertexAIBatchEmbeddings: pass\nclass GoogleBatchEmbeddings: pass\n")
create_mock_module("litellm/llms/vertex_ai/image_generation/image_generation_handler.py", "class VertexAIImageGeneration: pass\nclass VertexImageGeneration: pass\n")
create_mock_module("litellm/llms/vertex_ai/multimodal_embeddings/embedding_handler.py", "class VertexAIMultimodalEmbeddings: pass\nclass VertexMultimodalEmbedding: pass\n")
create_mock_module("litellm/integrations/custom_logger.py", "class CustomLogger:\n    def __init__(self, *a, **k): pass\nclass Span:\n    pass\n")
