import os

def create_mock_module(path, content=""):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)

# Integrations needed by core modules
create_mock_module("litellm/integrations/__init__.py")
create_mock_module("litellm/integrations/gcs_bucket/__init__.py")
create_mock_module("litellm/integrations/gcs_bucket/gcs_bucket_base.py", "class GCSBucketBase:\n    pass\n")

# Some core remote LLMs modules that are heavily referenced
for llm in ["anthropic", "bedrock", "vertex_ai", "azure_ai", "gemini", "azure", "openai_like", "xai"]:
    create_mock_module(f"litellm/llms/{llm}/__init__.py")

# Let's see what else fails, but try to use mocks this time so we don't mess up main.py imports.
# In a previous step I removed the remote LLMs entirely, so we'll probably need some mock files inside litellm/llms
create_mock_module("litellm/llms/anthropic/common_utils.py", "class AnthropicModelInfo:\n    pass\n")
create_mock_module("litellm/llms/anthropic/chat/__init__.py")
create_mock_module("litellm/llms/anthropic/chat/transformation.py", "class AnthropicConfig:\n    pass\n")
create_mock_module("litellm/llms/cohere/__init__.py")
create_mock_module("litellm/llms/cohere/chat/__init__.py")
create_mock_module("litellm/llms/cohere/chat/transformation.py", "class CohereGlobalConfig:\n    pass\nclass CohereConfig:\n    pass\n")
create_mock_module("litellm/llms/bedrock/chat/__init__.py")
create_mock_module("litellm/llms/bedrock/chat/invoke_handler.py", "class BedrockGlobalConfig:\n    pass\nbedrock_tool_name_mappings = {}\nclass MockResponseIterator:\n    def __init__(self, *a, **k): pass\n    def __iter__(self): return self\n    def __next__(self): raise StopIteration\n")
create_mock_module("litellm/llms/vertex_ai/text_embeddings/__init__.py")
create_mock_module("litellm/llms/vertex_ai/text_embeddings/transformation.py", "class VertexAITextEmbeddingConfig:\n    pass\n")
create_mock_module("litellm/llms/sagemaker/__init__.py")
create_mock_module("litellm/llms/sagemaker/chat/__init__.py")
create_mock_module("litellm/llms/sagemaker/chat/transformation.py", "class SagemakerConfig:\n    pass\n")
create_mock_module("litellm/llms/petals/__init__.py")
create_mock_module("litellm/llms/petals/chat/__init__.py")
create_mock_module("litellm/llms/petals/chat/transformation.py", "class PetalsConfig:\n    pass\n")
create_mock_module("litellm/llms/nlp_cloud/__init__.py")
create_mock_module("litellm/llms/nlp_cloud/chat/__init__.py")
create_mock_module("litellm/llms/nlp_cloud/chat/transformation.py", "class NLPCloudConfig:\n    pass\n")
create_mock_module("litellm/llms/replicate/__init__.py")
create_mock_module("litellm/llms/replicate/chat/__init__.py")
create_mock_module("litellm/llms/replicate/chat/transformation.py", "class ReplicateConfig:\n    pass\n")
create_mock_module("litellm/llms/databricks/__init__.py")
create_mock_module("litellm/llms/databricks/chat/__init__.py")
create_mock_module("litellm/llms/databricks/chat/transformation.py", "class DatabricksConfig:\n    pass\n")
create_mock_module("litellm/llms/empower/__init__.py")
create_mock_module("litellm/llms/empower/chat/__init__.py")
create_mock_module("litellm/llms/empower/chat/transformation.py", "class EmpowerConfig:\n    pass\n")
create_mock_module("litellm/llms/ai21/__init__.py")
create_mock_module("litellm/llms/ai21/chat/__init__.py")
create_mock_module("litellm/llms/ai21/chat/transformation.py", "class AI21ChatConfig:\n    pass\nAI21Config = AI21ChatConfig\n")
create_mock_module("litellm/llms/deprecated_providers/__init__.py")
create_mock_module("litellm/llms/deprecated_providers/palm.py", "class PalmConfig:\n    pass\n")
create_mock_module("litellm/llms/deprecated_providers/aleph_alpha.py", "class AlephAlphaConfig:\n    pass\n")
create_mock_module("litellm/llms/baseten/__init__.py")
create_mock_module("litellm/llms/baseten/chat/__init__.py")
create_mock_module("litellm/llms/baseten/chat/transformation.py", "class BasetenConfig:\n    pass\n")
create_mock_module("litellm/llms/cloudflare/__init__.py")
create_mock_module("litellm/llms/cloudflare/chat/__init__.py")
create_mock_module("litellm/llms/cloudflare/chat/transformation.py", "class CloudflareChatConfig:\n    pass\nCloudflareConfig = CloudflareChatConfig\n")
create_mock_module("litellm/llms/gemini/common_utils.py", "class GeminiModelInfo: pass\ndef get_gemini_base_url(*a, **k): return ''\n")
create_mock_module("litellm/llms/gemini/chat/__init__.py")
create_mock_module("litellm/llms/gemini/chat/transformation.py", "class GeminiConfig:\n    pass\n")
create_mock_module("litellm/llms/huggingface/__init__.py")
create_mock_module("litellm/llms/huggingface/chat/__init__.py")
create_mock_module("litellm/llms/huggingface/chat/transformation.py", "class HuggingfaceConfig:\n    pass\n")
create_mock_module("litellm/llms/oobabooga/__init__.py")
create_mock_module("litellm/llms/oobabooga/chat/__init__.py")
create_mock_module("litellm/llms/oobabooga/chat/transformation.py", "class OobaboogaConfig:\n    pass\n")
create_mock_module("litellm/llms/openrouter/__init__.py")
create_mock_module("litellm/llms/openrouter/chat/__init__.py")
create_mock_module("litellm/llms/openrouter/chat/transformation.py", "class OpenrouterConfig:\n    pass\n")
create_mock_module("litellm/llms/together_ai/__init__.py")
create_mock_module("litellm/llms/together_ai/chat/__init__.py")
create_mock_module("litellm/llms/together_ai/chat/transformation.py", "class TogetherAIConfig:\n    pass\n")
create_mock_module("litellm/llms/vertex_ai/chat/__init__.py")
create_mock_module("litellm/llms/vertex_ai/chat/transformation.py", "class VertexAIConfig:\n    pass\n")
create_mock_module("litellm/llms/maritalk/__init__.py")
create_mock_module("litellm/llms/maritalk/chat/__init__.py")
create_mock_module("litellm/llms/maritalk/chat/transformation.py", "class MaritalkConfig:\n    pass\n")
create_mock_module("litellm/llms/vertex_ai/vertex_embeddings/__init__.py")
create_mock_module("litellm/llms/vertex_ai/vertex_embeddings/transformation.py", "class VertexAITextEmbeddingConfig:\n    pass\n")
create_mock_module("litellm/llms/bedrock/embed/__init__.py")
create_mock_module("litellm/llms/bedrock/embed/amazon_titan_v2_transformation.py", "class BedrockTitanV2EmbeddingConfig:\n    pass\n")
create_mock_module("litellm/llms/bedrock/embed/amazon_titan_multimodal_transformation.py", "class BedrockTitanMultimodalEmbeddingConfig:\n    pass\n")
create_mock_module("litellm/llms/bedrock/embed/cohere_transformation.py", "class BedrockCohereEmbeddingConfig:\n    pass\n")
create_mock_module("litellm/llms/azure_ai/chat/__init__.py")
create_mock_module("litellm/llms/azure_ai/chat/transformation.py", "class AzureAIStudioConfig:\n    pass\n")
create_mock_module("litellm/llms/azure/responses/__init__.py")
create_mock_module("litellm/llms/azure/responses/transformation.py", "class AzureOpenAIResponsesAPIConfig:\n    pass\n")
create_mock_module("litellm/llms/azure/responses/o_series_transformation.py", "class AzureOpenAIOSeriesResponsesAPIConfig:\n    pass\n")
create_mock_module("litellm/llms/azure/chat/__init__.py")
create_mock_module("litellm/llms/azure/chat/o_series_transformation.py", "class AzureOpenAIO1Config:\n    pass\n")
create_mock_module("litellm/llms/azure/azure.py", "class AzureOpenAIAssistantsAPIConfig:\n    pass\n")
create_mock_module("litellm/llms/azure/chat/gpt_transformation.py", "class AzureOpenAIConfig:\n    pass\n")
create_mock_module("litellm/llms/azure/chat/gpt_5_transformation.py", "class AzureOpenAIGPT5Config:\n    pass\n")
create_mock_module("litellm/llms/azure/completion/__init__.py")
create_mock_module("litellm/llms/azure/completion/transformation.py", "class AzureOpenAITextConfig:\n    pass\n")
create_mock_module("litellm/llms/azure/audio_transcription/__init__.py")
create_mock_module("litellm/llms/azure/audio_transcription/transformation.py", "class AzureSpeechAudioTranscriptionConfig:\n    pass\n")
create_mock_module("litellm/llms/xai/__init__.py")
create_mock_module("litellm/llms/xai/responses/__init__.py")
create_mock_module("litellm/llms/xai/responses/transformation.py", "class XAIResponsesAPIConfig:\n    pass\n")
create_mock_module("litellm/llms/xai/common_utils.py", "class XAIModelInfo:\n    @staticmethod\n    def is_xai_route(*a, **k): return False\n")
create_mock_module("litellm/llms/xai/cost_calculator.py", "def cost_per_token(*a, **k): return 0.0, 0.0\n")
create_mock_module("litellm/llms/xai/realtime/__init__.py")
create_mock_module("litellm/llms/xai/realtime/handler.py", "class XAIRealtime: pass\n")
create_mock_module("litellm/llms/bedrock/embed/amazon_titan_v2_transformation.py", "class BedrockTitanV2EmbeddingConfig:\n    pass\nclass AmazonTitanV2Config:\n    pass\n")
create_mock_module("litellm/llms/bedrock/embed/amazon_titan_multimodal_transformation.py", "class BedrockTitanMultimodalEmbeddingConfig:\n    pass\nclass AmazonTitanMultimodalConfig:\n    pass\n")
create_mock_module("litellm/llms/bedrock/embed/cohere_transformation.py", "class BedrockCohereEmbeddingConfig:\n    pass\nclass CohereEmbeddingConfig:\n    pass\n")
create_mock_module("litellm/llms/litellm_proxy/__init__.py")
create_mock_module("litellm/llms/litellm_proxy/responses/__init__.py")
create_mock_module("litellm/llms/litellm_proxy/responses/transformation.py", "class LiteLLMProxyResponsesAPIConfig:\n    pass\n")
create_mock_module("litellm/llms/volcengine/__init__.py")
create_mock_module("litellm/llms/volcengine/responses/__init__.py")
create_mock_module("litellm/llms/volcengine/responses/transformation.py", "class VolcEngineResponsesAPIConfig:\n    pass\n")
create_mock_module("litellm/llms/manus/__init__.py")
create_mock_module("litellm/llms/manus/responses/__init__.py")
create_mock_module("litellm/llms/manus/responses/transformation.py", "class ManusResponsesAPIConfig:\n    pass\n")
create_mock_module("litellm/llms/perplexity/responses/__init__.py")
create_mock_module("litellm/llms/perplexity/responses/transformation.py", "class PerplexityResponsesConfig:\n    pass\n")
create_mock_module("litellm/llms/databricks/responses/__init__.py")
create_mock_module("litellm/llms/databricks/responses/transformation.py", "class DatabricksResponsesAPIConfig:\n    pass\n")
create_mock_module("litellm/llms/openrouter/responses/__init__.py")
create_mock_module("litellm/llms/openrouter/responses/transformation.py", "class OpenRouterResponsesAPIConfig:\n    pass\n")
create_mock_module("litellm/llms/bedrock_mantle/responses/__init__.py")
create_mock_module("litellm/llms/bedrock_mantle/responses/transformation.py", "class BedrockMantleResponsesAPIConfig:\n    pass\n")
create_mock_module("litellm/llms/gemini/interactions/__init__.py")
create_mock_module("litellm/llms/gemini/interactions/transformation.py", "class GoogleAIStudioInteractionsConfig:\n    pass\n")
create_mock_module("litellm/llms/openai/responses/__init__.py")
create_mock_module("litellm/llms/openai/responses/transformation.py", "class OpenAIResponsesAPIConfig:\n    pass\n")
